-- Insert a new inspection
INSERT IGNORE INTO inspections
  (inspection_visit_id,
   license_id,
   inspection_number,
   visit_number,
   inspection_class,
   inspection_type,
   inspection_disposition,
   inspection_date,
   total_violations,
   high_priority_violations,
   intermediate_violations,
   basic_violations,
   pda_status,
   county_number,
   license_number,
   created_on,
   modified_on)
VALUES (:inspection_visit_id,
   :license_id,
   :inspection_number,
   :visit_number,
   :inspection_class,
   :inspection_type,
   :inspection_disposition,
   :inspection_date,
   :total_violations,
   :high_priority_violations,
   :intermediate_violations,
   :basic_violations,
   :pda_status,
   :county_number,
   :license_number,
   :created_on,
   :modified_on);
